emcc ^
    -w ^
    -O2 ^
    -std=c99 ^
    -fdeclspec ^
    -o docs/index.html ^
    -s WASM=1 ^
    -s EMULATE_FUNCTION_POINTER_CASTS=1 ^
    -s USE_WEBGL2=1 ^
    -s USE_GLFW=3 ^
    -s FULL_ES3=1 ^
    -s USE_FREETYPE=1 ^
    -s USE_OGG=1 ^
    --embed-file assets/shaders/sprite.frag ^
    --embed-file assets/shaders/sprite.vs ^
    --embed-file assets/shaders/particle.frag ^
    --embed-file assets/shaders/particle.vs ^
    --embed-file assets/levels/four.lvl ^
    --embed-file assets/levels/one.lvl ^
    --embed-file assets/levels/three.lvl ^
    --embed-file assets/levels/two.lvl ^
    --preload-file assets/textures/awesomeface.png ^
    --preload-file assets/textures/background.jpg ^
    --preload-file assets/textures/block_solid.png ^
    --preload-file assets/textures/block.png ^
    --preload-file assets/textures/out.png ^
    --preload-file assets/textures/paddle.png ^
    --preload-file assets/textures/particle.png ^
    --use-preload-plugins ^
    -D__EMSCRIPTEN__ ^
    -DGLIB_COMPILATION ^
    -DG_DISABLE_CHECKS ^
    -DGOBJECT_COMPILATION ^
    -I./include ^
    -I./.lib/zerog/include ^
    -I./.lib/soil/include ^
    -I./.lib/glm/include ^
    -IC:/Users/darko/Documents/GitHub/glib ^
    -IC:/Users/darko/Documents/GitHub/glib/glib ^
    -IC:/Users/darko/Documents/GitHub/glib/gobject ^
    -IC:/msys64/mingw64/lib/libffi-3.2.1/include ^
    @files